services:
  backend:
    build: ../server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build: ../client
    ports:
      - "3001:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
